controller_class: ZeroRPCClient
controller_kwargs:
  ip_address: "172.16.0.1"
  controller_class: PolyMetisController
  controller_kwargs:
    controller_type: CARTESIAN_DELTA
    ip_address: localhost
control_hz: 10
random_init: False
img_width: 224
img_height: 224
horizon: 250
normalize_actions: True
channels_first: False
cameras:
  side_left:
    camera_class: OpenCVCamera
    camera_kwargs:
      id: /dev/video12
  side_right:
    camera_class: OpenCVCamera
    camera_kwargs:
      id: /dev/video14
  frontview:
    camera_class: OpenCVCamera
    camera_kwargs:
      id: /dev/video16
