
controller_class: ZeroRPCClient
controller_kwargs:
  ip_address: "172.16.0.1"
  controller_class: PolyMetisController
  controller_kwargs:
    controller_type: CARTESIAN_EULER_DELTA
    ip_address: localhost
control_hz: 10
random_init: True
img_width: 128
img_height: 128
horizon: 250
normalize_actions: True
channels_first: True
cameras:
  agent:
    camera_class: RealSenseCamera
    camera_kwargs:
      serial_number: '832112071449'
  wrist:
    camera_class: RealSenseCamera
    camera_kwargs:
      serial_number: '838212072814'
