
controller_class: ZeroRPCClient
controller_kwargs:
  ip_address: "172.16.0.130"
  controller_class: PolyMetisController
  controller_kwargs:
    ip_address: localhost
controller_type: CARTESIAN_EULER_DELTA
control_hz: 10
random_init: True
img_width: 256
img_height: 256
horizon: 250
channels_first: False
cameras:
  agent:
    camera_class: RealSenseCamera
    camera_kwargs:
      serial_number: '832112071449'
  wrist:
    camera_class: RealSenseCamera
    camera_kwargs:
      serial_number: '838212072814'
